recipients:
- name: admin
  public_key: age1se1q03mmy4d3gd4krnggvw7rzle3dfqpc4r2q7tfncgerfcdp26s2f0gyc4l53
  username: kig
  break_glass: false
- name: break-glass
  public_key: age1rzch7ekn54hv66sc4f46h4h7q2qvzhdgcjkl07c0dcac2snt45uq70pml5
  break_glass: true
encrypted_globs:
- '*.encrypted'
- .env.encrypted
- config/*.encrypted.yaml
sops_version: 3.13.2
join_request_ttl: 72h
